### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#11]
Find a way to setup session timeout.

Actually, user session is closed too quickly

**Comment by nicolas-lefloch** [comment]
Est-ce qu'ajouter ceci à **[LoginServlet](https://github.com/TimeboardIO/timeboard/blob/0ee72d45e70c40c1551be7ce328f6e0a6a4e4af5/security/src/main/java/timeboard/security/LoginServlet.java)** ne suffirait pas ?
`            session.setMaxInactiveInterval(sessionTimeoutInSeconds);
`
