### ISSUE TITLE
Changement d'utilisateur sur une tâche avec des imputations

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#133]
#1 : créer une tâche assignée à un utilisateur /1
#2 : l'utilisateur /1 fait des imputations sur la tâche
#3 : on change l'utilisateur (1 vers 2) assigné à la tâche
#4 : l'utilisateur /2 impute sur la tâche

Bug ?

L'utilisateur 1 doit-il voir dans son Timesheet une ligne relative à une tâche à laquelle il n'est plus assigné ?

**Comment by pierremellet** [comment]
Je pense qu'il faut ajouter une ligne dans le TS d'un utilisateur à patrir du moment où il a imputé au moins une fois.

**Comment by Jean-GuillaumeT** [comment]
RG :
à l'import de tâches d'une source externe, on sépare les tâches en 3 catégories : à créer, à modifier, à supprimer.
	à créer : "facile"
	à modifier : si l'assigné est différent alors on clot la tâche existante et on crée une nouvelle tâche pour le nouvel assigné
	à supprimer : on rend les tâches inactives ssi l'ES est à 0 dessus (sinon l'utilisateur ne les voit plus dans sa timesheet)

RG :
dans la modification des tâches, si l'ES d'une tâche est à 0 et que son origine est interne, alors on ne peut pas modifier l'assigné
