### ISSUE TITLE
User with role other than owner must not be able to setup project 

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#220]
Task creation/edition is allowed

**Comment by ClareneSzymalka** [comment]
Hypothèse prise: On ne peut pas changer son rôle, c'est un autre OWNER du projet qui peut changer notre rôle (cela oblige d'avoir un autre owner pour éviter qu'un projet ne se retrouve sans aucun owner)

Possible de changer cette hypothèse au besoin (dev à priori simple)
