### ISSUE TITLE
Group tasks to batch

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#223]

**Comment by Jean-GuillaumeT** [comment]
A batch is a group of tasks. A milestone is just a specific kind of batch with a date attached to it.

**Comment by pierremellet** [comment]
- Rename milestone to batch
- Rename milestone_type to batch_type
- rename BILL -> BILL_MILESTONE
- rename DELIVERY -> DELIVERY_MILESTONE

**Comment by pierremellet** [comment]
Add a dropdown list on project's tasks page that allow user to select a grouping strategy.
Each strategy come from batch type.

E.g : group by spring, bill, request


For each group display KPI (0E, RE, ES, EL)
