### ISSUE TITLE
Import calendars

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#24]
Find a way to import calendars from external files from Karaf shell command (iCal ?) :
- A calendar has a unique pk
- A calendar has a unique name across Timeboard instance
- A calendar has a default imputation option : set default value to 1.0 into timesheet
- A calendar can't be removed if there is one imputation on event

Each project can subscribe to a calendar.

Calendar events must be diplayed into users timesheets as a task.

If user is member of multiple projects and projects are subscribe to the same calendar. User only view one calendar

**Comment by nicolas-lefloch** [comment]
Already done #93 include in #103
