### ISSUE TITLE
Display commit id when mouse is hover application title

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#275]
Add an area at bottom left of each window that allow user to display application version number.
Version number is only displayed when mouse is over this area.
A click on this area add commit number to user clipboard (useful for issues creation).

Version number may be commit id provided by a sed command on application.properties from eb.sh script

**Comment by ClareneSzymalka** [comment]
not hover application title but hover an invisible box ont the bottom left of the pages
