### ISSUE TITLE
Can't delete task

### ISSUE THREAD

**Issue by nicolas-lefloch** [TimeboardIO/timeboard#316]
Foreign key broken when one project snapshot is created.

Archive task ?

**Comment by ClareneSzymalka** [comment]
- Est ce qu'il faudrait partir une solution d'archivage des tasks et non plus sur une suppression des tasks

**Comment by ClareneSzymalka** [comment]
On ne supprime jamais de tâche, on part du principe qu'on les archive
Ajout d'un "ARCHIVED" dans le statut de la tâche

Si archivage d'une tâche dans le cas où il y a des imputations: 
- avertissement donné à l'utilisateur
- la tâche devient "grisée" dans le timesheet et impossible d'imputer dessus
