### ISSUE TITLE
Restrict vacation validation to selected users (with a certain role or attribute)

### ISSUE THREAD

**Issue by Jean-GuillaumeT** [TimeboardIO/timeboard#327]
attribut ou droit de validation et restriction du choix des valideurs parmi cette liste pour les demandes de congés
gestion du droit/rôle des utilisateurs par l'owner de l'organisation

**Comment by ClareneSzymalka** [comment]
Dans un premier temps, la liste des "user notified" doit contenir tous les project Owner des projects dont je suis membre

**Comment by ClareneSzymalka** [comment]
Dans un premier temps, on part sur le principe qu'on peut uniquement demander un congé à un des project owner des project dont je suis membre
