### ISSUE TITLE
Week's submission and validation status indicator

### ISSUE THREAD

**Issue by ClareneSzymalka** [TimeboardIO/timeboard#342]
Sur la vue de la timesheet, je peux voir deux voyants :
- un voyant concernant la soumission ou non de la semaine
- un voyant concernant la validation ou non de la semaine

Sur la vue de la timesheet, je peux voir un message en cas de non soumission de la semaine précédente ou de non validation d'une des semaines précédentes

Suivre les mêmes labels/couleurs que ceux de la version actuelle d'ePO

**Comment by pierremellet** [comment]
On a déjà un système qui permet connaitre de la soumission ou non de la semaine

![image](https://user-images.githubusercontent.com/2440503/72976823-9a0a9500-3dd3-11ea-9594-28296835a48e.png)

**Comment by pierremellet** [comment]
On peut continuer dans la logique ergonomique d'un bouton/label, au même endroit dans l'UI et qui change d'état en fonction de l'avancement du timesheet dans le processus de validation

![image](https://user-images.githubusercontent.com/2440503/72977117-1ef5ae80-3dd4-11ea-8b6d-113c605630c4.png)

![image](https://user-images.githubusercontent.com/2440503/72977170-3cc31380-3dd4-11ea-8bc3-579175865532.png)
