### ISSUE TITLE
Error when i want to display project tasks

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#345]
When i want to edit projet's tasks (473), i have an error.

![image](https://user-images.githubusercontent.com/2440503/72255476-1e585d80-3607-11ea-8155-bad03f8d2962.png)

**Comment by nicolas-lefloch** [comment]
Due to the removal of labels in enums. Will fix it with #321

**Comment by nicolas-lefloch** [comment]
Fix in MR #348
