### ISSUE TITLE
Can not list organization member of public org

### ISSUE THREAD

**Issue by nicolas-lefloch** [TimeboardIO/timeboard#351]
List organization member of public org is empty

**Comment by pierremellet** [comment]
Ça me semble normal, tous le monde à accès à une org publique, ça évite de voir tout le contenu de la base.

Les accounts sont membres par défaut d'une org publique sans entrées dans la table orga membership

**Comment by nicolas-lefloch** [comment]
Du coup on ne peut ajouter personne à nos projets ?

**Comment by Jean-GuillaumeT** [comment]
Problème résolu par suppression de la public org
