### ISSUE TITLE
Improve vacations tab UX

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#369]
Unusable on mobile devices, 

If i have many requests, calendar view is translated faaaaar away to the bottom of page.
Split view into two cols on desktop, left contains calendar and right contains request ?

Month row may be too heigth ?

![image](https://user-images.githubusercontent.com/2440503/72604144-a184f680-391a-11ea-844b-98a9be92cce5.png)

**Comment by nicolas-lefloch** [comment]
- Séparation en deux onglets
 -- requêtes
 -- calendrier
- Affichage d'un scroll bar horizontal si l'écran ne permet pas l'affichage de tout le calendrier
