### ISSUE TITLE
New user should have directly access to the public organization

### ISSUE THREAD

**Issue by ClareneSzymalka** [TimeboardIO/timeboard#384]
Lorsqu'on utilise le compte d'un nouvel utilisateur, celui-ci n'est pas directement ajouté à l'organisation publique alors qu'il le devrait
Sa vue de l'application est donc vide

**Comment by pierremellet** [comment]
Bug depuis la mise en place de l'ABAC.

Dans le cas d'une organisation publique, il serait judicieux de ne pas créer une relation "OrganisationMembership" pour tout le monde.
On peut déduire cette information d'un attribut sur l'organisation (SETUP_PUBLIC).

Il faut donc une policy qui permette de dire qu'un utilisateur peut accéder à certaines fonctions en fonction de son role sur la ressource ou si cette dernière est publique
