### ISSUE TITLE
Red / Green badge on timesheet total row

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#39]
Mettre à jour l'écran du timesheet : 

- Si la somme des imputations d'une journée == 1 alors le badge est vert

- Si la somme des imputations d'une journée == 0 alors le badge est rouge

**Comment by nicolas-lefloch** [comment]
Il y a deux ou trois états ? 
0 : rouge , ]0-1[ : gris ,  1 : vert
