### ISSUE TITLE
Add task end date and user name on timesheet

### ISSUE THREAD

**Issue by nicolas-lefloch** [TimeboardIO/timeboard#410]
On Timesheet view
- Add task end date before task name (format 31-Jan-2020)
- Add screen name on top left cell (blue)

**Comment by pierremellet** [comment]
Une deuxième fois le nom de l'utilisateur sur l'écran ?

Il est déjà en haut à droite.

Qu'est ce qui justifie ça ?

**Comment by nicolas-lefloch** [comment]
Comme les managers peuvent consulter les timesheets des autres utilisateurs, il manque l'information du propriétaire de la timesheet que l'on consulte.

**Comment by pierremellet** [comment]
On est donc sur un problème d'impersonation et pas uniquement coller un label.

C'est quoi la conception ?
