### ISSUE TITLE
[Timesheet] Make the table configurable

### ISSUE THREAD

**Issue by ClareneSzymalka** [TimeboardIO/timeboard#434]
Rendre le tableau configurable afin de laisser la possibilité à l'utilisateur d'afficher uniquement les colonnes de son choix

**Comment by ClareneSzymalka** [comment]
PME: Attention, le Timesheet est un objet très lourd à calculer et qui sera très probablement le plus utilisé. Faut bien trancher entre envie et besoin pour ne pas tuer l’application avec du calcul d’information le vendredi soir.

**Comment by nicolas-lefloch** [comment]
Affichage / Masquage des colonnes côté front de la même manière que le composant datatable. Cela ne n'entrainera pas de calculs supplémentaire côté back.

**Comment by nicolas-lefloch** [comment]
Waiting for #410 & #440

**Comment by ClareneSzymalka** [comment]
Doublon avec l'Issue #477
