### ISSUE TITLE
Labels en francais

### ISSUE THREAD

**Issue by DelphineLb** [TimeboardIO/timeboard#46]
Actuellement, les labels de l'application sont en anglais.  Il faudrait les passer en français.

**Comment by pierremellet** [comment]
Il faut prévoir une ihm multilingues ou full français ?

**Comment by DelphineLb** [comment]
Francais pour le moment ca sera suffisant. En revanche fichiers fe label externalisé pour pouvoir modifier facilement sans tout recompiler 
On fera une evol ultérieure pour l internationalisation.

**Comment by nicolas-lefloch** [comment]
Vu la taille du dictionnaire de l'application actuel, un fichier externe, injecté par **TimeboardServlet** dans le _viewModel_ de toutes les pages ne pourrait pas faire l'affaire ?

**Comment by pierremellet** [comment]
Voir pour l'utilisation des fragments bundles
