### ISSUE TITLE
No input controls on OE

### ISSUE THREAD

**Issue by nicolas-lefloch** [TimeboardIO/timeboard#513]
Limit OE input to 0.05 step

![Capture du 2020-02-24 14-45-49](https://user-images.githubusercontent.com/15018911/75157484-8032d980-5714-11ea-8951-fc2459fddd9e.png)
![Capture du 2020-02-24 14-45-35](https://user-images.githubusercontent.com/15018911/75157485-80cb7000-5714-11ea-9764-6bf7b30412a9.png)

**Comment by ClareneSzymalka** [comment]
Utilisation du <number-input> dans le formulaire de task
