### ISSUE TITLE
Can not see assigned tasks on timesheet in production 

### ISSUE THREAD

**Issue by nicolas-lefloch** [TimeboardIO/timeboard#524]

**Comment by nicolas-lefloch** [comment]
![Capture du 2020-02-24 17-57-21](https://user-images.githubusercontent.com/15018911/75173426-21c72480-572f-11ea-81a1-89b45ee1c6f8.png)
![Capture du 2020-02-24 17-57-08](https://user-images.githubusercontent.com/15018911/75173429-225fbb00-572f-11ea-9765-cd2036099f95.png)

**Comment by pierremellet** [comment]
Non reproductible
