### ISSUE TITLE
Standardization of update forms

### ISSUE THREAD

**Issue by nicolas-lefloch** [TimeboardIO/timeboard#549]
Actuellement les formulaires d'édition manquent d’homogénéité (label des bouton, mode de fonctionnement différent), pas ou peu de retours utilisateur sur le succès / échec de l'opération.

Le plus clair a ce moment est le formulaire de CRUD de type de tâche.

![Capture du 2020-02-26 10-01-05](https://user-images.githubusercontent.com/15018911/75328837-ef2c4180-587e-11ea-967a-7b93c9c06ef8.png)
![Capture du 2020-02-26 10-00-49](https://user-images.githubusercontent.com/15018911/75328838-efc4d800-587e-11ea-9a22-b05d5cffa442.png)
![Capture du 2020-02-26 10-00-29](https://user-images.githubusercontent.com/15018911/75328839-efc4d800-587e-11ea-8329-bebbb151b5c2.png)
![Capture du 2020-02-26 10-00-14](https://user-images.githubusercontent.com/15018911/75328842-f05d6e80-587e-11ea-84eb-1176c52a9345.png)
![Capture du 2020-02-26 09-59-59](https://user-images.githubusercontent.com/15018911/75328844-f05d6e80-587e-11ea-94bc-6b506bf4c41b.png)
![Capture du 2020-02-26 09-59-29](https://user-images.githubusercontent.com/15018911/75328847-f0f60500-587e-11ea-9933-30262a752bd2.png)
![Capture du 2020-02-26 10-02-15](https://user-images.githubusercontent.com/15018911/75328950-197dff00-587f-11ea-924f-4f6ba11a8369.png)

**Comment by ClareneSzymalka** [comment]
En dessous de 3 champs, on utilise un formulaire du type "TASK TYPE"
Au dessus de 3 champs, on utilise une modal qui contiendra le formualire
