### ISSUE TITLE
Add milestones to project

### ISSUE THREAD

**Issue by pierremellet** [TimeboardIO/timeboard#60]
Project has milestones

Milestone
- pk
- name
- date  
- type (bill, delivery, input, scheduling)
- attributs (Map<String, String> 0..*)
- tasks (List<Task> 0..*)
 
Add a section to project setup to CRUD a milestone

**Comment by ClareneSzymalka** [comment]
"Add a section to project setup to CRUD a milestone" -> Add a new tab "Milestone" to centralize milestones's datas
