### ISSUE TITLE
Add calendar import

### ISSUE THREAD

**Issue by Jean-GuillaumeT** [TimeboardIO/timeboard#93]
### ICS / ICAL
_Éléments de la norme ICAL gardé dans le projet_
PRODID: identifiant unique du calendar
- DTSTART: date de début
- DTEND: date de fin
- SUMMARY: nom de l'event
- DESCRIPTION: description 
- RRULE: Règles de récurence
  + REQ: DAILY, WEEKLY, MOUNTLY, YEARLY,...
  + COUNT: nb de récurences;
  + UNTIL: date de fin de récurence
   + INTERVAL: intervale entre les élements (ex: RRULE:FREQ=DAILY;INTERVAL=10;COUNT=5 tout les 10 jours, 5 occurrences)

### IMPORT
Library : Ical4J
Même mécanique (origin + remoteId) que l'import de tâches;
Lister les évents : 
	Création :
	- Si remoteId inexistant en DB
	- Dupliquer les évents récurents leurs mettre un même remoteId
	Mise à jour
	- Si remoteId présent en DB
	- Chercher les évents récurents (même remoteId), générer la liste des nouveaux évents + faire la différence (crud)
	Suppression
	- Si remoteId présent en DB et disparu de l'origin
	- Seulement si aucune imputations sur l'event

### MODÉLISATION
- Calendar : création d'un objet dans le modèle
- Event = DefaultTask
Remonter origin/  remotePath / remoteId dans AbstractTask pour que les tâches par défaut en bénéficient
Event

**Comment by nicolas-lefloch** [comment]
## Questions fonctionnelles sur calendar

###  A l'import d'un calendar
- Pour les récurrences infinis, il faut limiter l'import dans le temps
	- quelle limite : 1mois ? 1 an ? (configuration ?, paramètre d'import ?)
	  dans le futur certains calendars seront liés à un projet, ont pourra définir la limite à la fin du projet
- Pour l'import de récurrence daily, l'implémentation actuelle va créer un évent par jour, cela créé donc un cascade dans timesheet

|| Monday | Tuesday | Wednesday | Thursday | Friday |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Daily  | [0] | | | | |
| Daily  | | [0] | | | |
| Daily  | | | [0] | | |
| Daily  | | | | [0] | |
| Daily  | | | | | [0] |

Serait-il justifié de fusionner ces évents pour n'en faire qu'un sur toutes la semaine ?

| | Monday | Tuesday | Wednesday | Thursday | Friday |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Daily  | [0] | [0] | [0] | [0] | [0] |

### A la suppression d'un calendar
- que faire des évent avec des imputations ?
	- supprimer uniquement les évents futur ?
	- les évents restant deviennent orphelins ?
	- Peut-on continuer à changer les imputations sur les évents orphelins ?

## Blocage technique sur l'import de fichier via OSGI/Jetty
Parsing et traitements métier OK
